### ISSUE TITLE
nan_typedarraycontents.h: API has changed

### ISSUE THREAD

**Issue by rgobbel** [tbouron/MMM-FlightTracker#15]
Node's API for ArrayBuffers has changed, as described in https://docs.google.com/document/d/1sTc_jRL87Fu175Holm5SV0kajkseGl2r8ifGY76G35k

In nan_typedarraycontents.h, this change (at line 34) makes it compile:

```C++
//      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
      std::shared_ptr<v8::BackingStore> backing = buffer->GetBackingStore();
      data   = static_cast<char*>(backing->Data()) + byte_offset;
```

**Comment by JHenzi** [comment]
This seems to have the module install entirely broken, the `npm i` command doesn't execute any longer because of an exception inside of electron-rebuild:

```
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 22.3.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 22.3.2 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-FlightTracker/node_modules/magicmirror-rebuild/node_modules/node-abi/index.js:39:9)
    at new Rebuilder (/home/pi/MagicMirror/modules/MMM-FlightTracker/node_modules/magicmirror-rebuild/build/rebuild.js:100:48)
    at rebuildWithOptions (/home/pi/MagicMirror/modules/MMM-FlightTracker/node_modules/magicmirror-rebuild/build/rebuild.js:249:23)
    at doRebuild (/home/pi/MagicMirror/modules/MMM-FlightTracker/node_modules/magicmirror-rebuild/build/rebuild.js:272:16)
    at /home/pi/MagicMirror/modules/MMM-FlightTracker/node_modules/magicmirror-rebuild/build/cli.js:115:45
npm ERR! code 255
npm ERR! path /home/pi/MagicMirror/modules/MMM-FlightTracker
npm ERR! command failed
npm ERR! command sh -c -- ./node_modules/.bin/MagicMirror-rebuild

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-03-18T06_23_20_343Z-debug-0.log
```
